name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install requests ruff

      - name: Run script
        run: ./fetch_python_docs.py --systemd

      - name: Check system service is active
        run: systemctl --user is-active python-docs

      - name: Ruff format & check
        run: |
          ruff format --check
          ruff check
